### ISSUE TITLE
Simplify CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [Continent43/prj-rev-bwfs-dasmoto#5]
It is a good idea to try and simplify the CSS code as much as you can to make the code cleaner and to remove repetitive code. There are a few shared properties in your CSS, which you can simplify like so,

```css
h1, h2, #price {
  font-family: Helvetica;
  font-weight: bold;
}

h1{
  font-size: 100px;
  color:khaki;
  text-align: center;
  background-image: url(https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg);
}

h2{ 
  font-size: 32px;
  color: white;
}

#brushes{
  background-color: mediumspringgreen
}

#frames{
  background-color: lightcoral;
}

#paint{
  background-color: skyblue;
}

#price{
  color: blue;
}
```
